"use strict";
const root=document.documentElement;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:0})}
function pnl(n){n=Number(n||0);return(n>=0?"+":"")+money(n)}
function dir(v){v=String(v||"").toUpperCase();if(v.includes("BUY")||v.includes("BULL")||v==="LONG")return"BUY";if(v.includes("SELL")||v.includes("BEAR")||v==="SHORT")return"SELL";return"NEUTRAL"}
function dirClass(v){const d=dir(v);return d==="BUY"?"buy":d==="SELL"?"sell":"neutral"}
function istDateKey(ms){try{return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(ms))}catch(e){return new Date(ms).toISOString().slice(0,10)}}
function dateLabel(key){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(key||"")))return key==="OTHER"?"Other":String(key||"Other");const today=istDateKey(Date.now());if(key===today)return"Today";if(key===istDateKey(Date.now()-86400000))return"Yesterday";const p=key.split("-");return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(+p[0],+p[1]-1,+p[2])))}
function sortDateKeys(keys){const today=istDateKey(Date.now());return keys.sort((a,b)=>{if(a===today&&b!==today)return-1;if(b===today&&a!==today)return 1;return b.localeCompare(a)})}
function timeLabel(ms){try{return new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(Number(ms)))+" IST"}catch(e){return""}}
function dateTimeLabel(value,ts){let ms=Number(ts||0);if(!ms)ms=Date.parse(String(value||""));if(!ms)return String(value||"");return dateLabel(istDateKey(ms))+" · "+timeLabel(ms)}
function signalCard(x){const d=dir(x.dir||x.direction||x.signal),stamp=x.ts_ms?dateTimeLabel(x.time,x.ts_ms):(x.time||x.timestamp||"");return `<div class="signal-card"><div class="signal-main"><div><div class="signal-symbol">${esc(x.sym||x.symbol||"—")}</div><div class="signal-meta">${esc(x.strategy||"Sweep")} · ${esc(stamp)}</div></div><div class="signal-right"><span class="signal-dir ${dirClass(d)}">${d}</span><div class="signal-status">${esc(x.status||"SIGNAL SAVED")}</div></div></div></div>`}
function renderSignals(list){const groups={};(list||[]).forEach(x=>{const k=x.date||String(x.time||x.timestamp||"").slice(0,10)||"OTHER";(groups[k]??=[]).push(x)});const keys=sortDateKeys(Object.keys(groups));return keys.length?keys.map(k=>`<div class="signal-date">${esc(dateLabel(k))}</div>${groups[k].sort((a,b)=>Number(b.ts_ms||0)-Number(a.ts_ms||0)).map(signalCard).join("")}`).join(""): '<div class="empty">No saved signals.</div>'}
function renderLatest(list){return(list||[]).slice(0,3).map(signalCard).join("")||'<div class="empty">No saved signals yet.</div>'}
function renderTrades(list){if(!list?.length)return'<div class="empty">No open trades</div>';return list.map(t=>{const d=String(t.direction||t.side||"").toUpperCase();return `<div class="row"><div class="rowtop"><b>${esc(t.symbol||"Trade")}</b><span class="badge ${d==="LONG"||d==="BUY"?"long":"short"}">${esc(d)}</span></div><div class="muted">${esc(t.strategy||"")} · Entry ${esc(t.entry??t.plan?.entry??"—")} · Current ${esc(t.current??"—")} · ${pnl(t.pnl_inr??t.pnl)}</div><div class="muted">SL ${esc(t.sl??t.plan?.stop_loss??"—")} · TP ${esc(t.tp??t.plan?.take_profit??"—")} · Qty ${esc(t.qty??"—")}</div></div>`}).join("")}
function renderAccounts(a){const keys=Object.keys(a||{});return keys.length?keys.map(k=>{const x=a[k]||{};return `<div class="row"><div class="rowtop"><b>${esc(x.name||k)}</b><span class="badge">${esc(x.daily_trades||0)} / ${esc(x.daily_limit||0)} trades</span></div><div class="muted">Balance ${money(x.balance)} · Today ${pnl(x.today_pnl)}</div></div>`}).join(""):'<div class="empty">No account data</div>'}
function renderHistory(list){if(!list?.length)return'<div class="empty">No closed trades yet.</div>';const groups={};list.forEach(x=>{const k=String(x.closed_at||x.close_time||x.time||"").slice(0,10)||"OTHER";(groups[k]??=[]).push(x)});return sortDateKeys(Object.keys(groups)).map(k=>`<div class="history-date">${esc(dateLabel(k))}</div>${groups[k].map(x=>{const v=Number(x.pnl||0),d=String(x.type||x.direction||"").toUpperCase(),side=d.includes("SHORT")||d.includes("SELL")?"SELL":"BUY";return `<div class="row"><div class="rowtop"><b>${esc(x.symbol||"Trade")}</b><span class="badge ${side==="BUY"?"long":"short"}">${side}</span></div><div class="muted">${esc(x.strat||x.strategy||"")} · ${esc(dateTimeLabel(x.closed_at||x.close_time||x.time||""))}</div><div><b>${pnl(v)}</b> <span class="muted">${esc(x.result||(v>=0?"WIN":"LOSS"))}</span></div></div>`}).join("")}`).join("")}
function renderNews(list){if(!list?.length)return'<div class="empty">No news available right now.</div>';return list.map(x=>{const impact=String(x.impact||"LOW").toLowerCase();return `<div class="news-item impact-${impact}"><div class="news-top"><div class="news-title">${esc(x.title||x.headline||x.event||"News")}</div><span class="impact ${impact}">${esc(impact.toUpperCase())}</span></div><div class="news-meta">${esc(x.source||x.publisher||x.provider||"Economic Calendar")} · ${esc(x.ts_ms?timeLabel(x.ts_ms):(x.time||x.timestamp||"Time unavailable"))}</div>${x.url||x.link?`<div class="news-link">${esc(x.url||x.link)}</div>`:""}</div>`}).join("")}
function drawCurve(points){const path=$("equityPath"),meta=$("curveMeta");if(!points||points.length<2){path.setAttribute("d","");meta.textContent=points?.length?"One equity point available":"Waiting for equity history…";return}const vals=points.map(x=>Number(x.equity)||0),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;path.setAttribute("d",points.map((x,i)=>{const px=30+760*i/(points.length-1),py=170-150*((Number(x.equity)-min)/span);return(i?"L":"M")+px.toFixed(1)+" "+py.toFixed(1)}).join(" "));meta.textContent=`Range ${money(min)} → ${money(max)} · ${points.length} points`}
function backtestMetric(l,v,c=""){return`<div class="metric"><b>${esc(l)}</b><strong class="${c}">${esc(v)}</strong></div>`}
function renderBacktest(raw,full){const el=full?$("result"):$("backtestOverview");const m=raw?.metrics||raw;if(!m){el.innerHTML='<div class="empty">No saved backtest.</div>';return}const total=Number(m.total_trades??m.trades??0),ret=Number(m.return_pct||0),wr=Number(m.win_rate||0),p=Number(m.total_pnl||0),fd=Number(m.final_balance||0),dd=Number(m.max_drawdown_pct||0);el.innerHTML='<div class="metric-grid">'+backtestMetric("Return",ret.toFixed(2)+"%",ret>=0?"bt-win":"bt-loss")+backtestMetric("Trades",total)+backtestMetric("Win Rate",wr.toFixed(2)+"%")+(full?backtestMetric("Total P&L",pnl(p),p>=0?"bt-win":"bt-loss")+backtestMetric("Final Balance",money(fd))+backtestMetric("Max Drawdown",dd.toFixed(2)+"%",dd>0?"bt-loss":"bt-flat"):"")+'</div>'}
function loadDashboard(){fetch("/api/dashboard",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(data=>{const ov=data.overview||{},curve=data.equity_curve||{};$("balance").textContent=money(ov.balance);$("equity").textContent=money(ov.equity??curve.current_equity);$("today").textContent=pnl(ov.today_pnl);$("open").textContent=String((data.live_trades||[]).length);$("total").textContent=pnl(data.total_pnl);$("updated").textContent=data.generated_at||"Live";$("headerUpdate").textContent=data.generated_at||"Live";$("headerState").textContent=ov.state||"ONLINE";$("statePill").textContent=ov.state||"ONLINE";$("riskPill").textContent=ov.risk_state||"NORMAL";drawCurve(curve.points||[]);$("accounts").innerHTML=renderAccounts(data.accounts);$("exposure").innerHTML=renderTrades(data.live_trades);$("latest").innerHTML=renderLatest(data.signals||[]);$("tradesList").innerHTML=renderTrades(data.live_trades);$("signalsList").innerHTML=renderSignals(data.signals||data.today_signals||[]);const hist=data.history||[];$("historyList").innerHTML=renderHistory(hist);$("hpnl").textContent=pnl(hist.reduce((s,x)=>s+Number(x.pnl||0),0));$("hcount").textContent=String(data.history_total??hist.length);$("hwin").textContent=(hist.length?Math.round(hist.filter(x=>Number(x.pnl||0)>0).length/hist.length*100):0)+"%";$("newsList").innerHTML=renderNews(data.news||data.news_raw||[]);try{const saved=JSON.parse(localStorage.getItem("mavis-last-backtest")||"null");if(saved)renderBacktest(saved,false)}catch(e){}}).catch(err=>{console.error(err);$("headerState").textContent="DEGRADED";$("statePill").textContent="DEGRADED";$("riskPill").textContent="CHECK"})}
function init(){document.querySelectorAll("#nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#nav button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.page).classList.add("active");scrollTo(0,0)});const menu=$("themeMenu"),btn=$("themeBtn");btn.onclick=e=>{e.stopPropagation();menu.classList.toggle("show")};document.querySelectorAll("[data-style][data-theme]").forEach(x=>x.onclick=()=>{root.dataset.style=x.dataset.style;root.dataset.theme=x.dataset.theme;localStorage.setItem("mavis-style",x.dataset.style);localStorage.setItem("mavis-theme",x.dataset.theme);menu.classList.remove("show")});document.querySelectorAll("[data-accent]").forEach(x=>x.onclick=()=>{root.dataset.accent=x.dataset.accent;localStorage.setItem("mavis-accent",x.dataset.accent)});try{root.dataset.style=localStorage.getItem("mavis-style")||"modern";root.dataset.theme=localStorage.getItem("mavis-theme")||"light";root.dataset.accent=localStorage.getItem("mavis-accent")||"green"}catch(e){}$("schedule").innerHTML=["09:15","10:15","11:15","12:15","13:15","14:15"].map(x=>`<div class="slot locked">${x}</div>`).join("");$("run").onclick=()=>{const box=$("result");box.innerHTML="Running backtest…";fetch(`/api/backtest?symbol=${encodeURIComponent($("bs").value)}&strategy=${encodeURIComponent($("bstr").value)}&days=${encodeURIComponent($("bd").value)}`,{cache:"no-store"}).then(r=>r.json()).then(d=>{if(d.error){box.innerHTML=`<div class="bt-error">Backtest error: ${esc(d.error)}</div>`;return}localStorage.setItem("mavis-last-backtest",JSON.stringify(d));renderBacktest(d,true)}).catch(e=>box.innerHTML=`<div class="bt-error">Backtest error: ${esc(e)}</div>`)};$("themeMenu").setAttribute("aria-hidden","true");loadDashboard();setInterval(loadDashboard,30000)}
document.addEventListener("DOMContentLoaded",init);
